(() => {
  const c=AD_SPECS,esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const toData=specs=>specs.map(s=>({media:s.platform==='Google'?'Google Ads':s.platform,format:s.name,lines:['【素材規格】',...s.rules.map(r=>'• '+r.label+'：'+r.value),'【文案規格】',...s.fields.map(f=>'• '+f.label+'（'+(f.requirement||(f.required?'必要':'選填'))+'）：'+(f.limit==null?'依後台選項':c.textLimit(s,f.limit))+(f.max>1?'；最多 '+f.max+' 則／行':'')+(f.note?'；'+f.note:'')),...(s.cards?['【每張圖卡】',...s.cards.fields.map(f=>'• '+f.label+'：'+c.textLimit(s,f.limit))]:[]),...(s.visual?['【附加素材】',...s.visual.map(r=>'• '+r.label+'：'+r.value)]:[]),'【提醒】',...s.notes.map(n=>'• '+n),'• Landing URL：確認網址有效／產品已上架，建議加上 UTM 追蹤參數。']}));
  function buildSheet(specs){const source=specs?toData(specs):data;const rows=[['媒體','廣告格式','製作規範']],merges=[];for(const s of source){const start=rows.length+1;for(let i=0;i<s.lines.length;i+=5)rows.push([i?'':s.media,i?'':s.format,s.lines.slice(i,i+5).join('\n')]);const end=rows.length;if(end>start)merges.push('A'+start+':A'+end,'B'+start+':B'+end);}return {name:'已選格式規格總表',rows,widths:[18,36,110],merges,editable:[],sections:[],validations:[]};}
  let data=[],html='',plain='';const status=document.getElementById('allSpecsStatus');
  function refresh(){data=toData(window.AdSelection.getFormats());const cell='border:1px solid #dce4f0;padding:12px;vertical-align:top;line-height:1.7;color:#23354f';html='<table style="border-collapse:collapse;width:100%;font-family:Microsoft JhengHei,Arial,sans-serif;font-size:12px"><thead><tr>'+['媒體','廣告格式','製作規範'].map(x=>'<th style="background:#173e92;color:white;padding:10px">'+x+'</th>').join('')+'</tr></thead><tbody>'+data.map(s=>'<tr><td style="'+cell+'">'+esc(s.media)+'</td><td style="'+cell+'">'+esc(s.format)+'</td><td style="'+cell+'">'+s.lines.map(esc).join('<br>')+'</td></tr>').join('')+'</tbody></table>';plain=data.map(s=>s.media+'｜'+s.format+'\n'+s.lines.join('\n')).join('\n\n────────────────────\n\n');document.getElementById('allSpecsContent').innerHTML=html;document.getElementById('specSummaryHint').textContent=(window.AdSelection.hasSelected()?'已選 '+data.length+' 個格式：':'尚未加入格式，輸出目前格式：')+data.map(s=>s.media+' '+s.format).join('、');document.getElementById('specSummaryToggle').textContent='查看本次 '+data.length+' 個格式的規格總表';status.textContent='';document.getElementById('copySpecsFallback').hidden=true;window.SpecSummary={data,html,plain,buildSheet};}
  window.addEventListener('ad-selection-change',refresh);refresh();
  document.getElementById('copyAllSpecs').onclick=async()=>{try{if(window.ClipboardItem&&navigator.clipboard.write)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([plain],{type:'text/plain'})})]);else await navigator.clipboard.writeText(plain);status.textContent='已複製本次規格；Email 可貼成表格，LINE 貼成分段文字。';}catch{const t=document.getElementById('copySpecsFallback');t.hidden=false;t.value=plain;t.focus();t.select();status.textContent='瀏覽器未允許剪貼簿；已選取本次規格，請按 Ctrl+C。';}};
  document.getElementById('downloadAllSpecs').onclick=async()=>{try{const bytes=await AdExcel.makeWorkbook([buildSheet()]);const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download='廣告素材規格總表_已選格式.xlsx';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='已下載：已選格式同一頁簽，三欄整理。';}catch{status.textContent='下載失敗，請重新整理後再試。';}};
  window.SpecSummary={data,html,plain,buildSheet};
})();
