/* Public Google Ads documentation checked 2026-10-06. Separate delivery forms by format. */
(() => {
  const catalog=window.AD_SPECS, g=n=>`https://support.google.com/google-ads/answer/${n}?hl=en`;
  const technical=g(13547298), reach=g(10510238), shorts=g(16041697), action=g(17141078);
  const f=(id,label,limit,required=false,note='',extra={})=>({id,label,limit,required,mode:'hard',min:1,max:1,note,...extra});
  const r=(label,value,type='官方規格')=>({label,value,type});
  const video=[r('建議解析度／比例','16:9：1920×1080；9:16：1080×1920；1:1：1080×1080 px','官方建議'),r('最低 HD 解析度','橫式 1280×720；直式 720×1280；方形 480×480 px；另接受 SD，不建議'),r('檔案與上架','MP4／MOV 等 YouTube 支援格式；≤256 GB；提供 YouTube 公開或不公開影片連結')];
  const banner=[r('Companion Banner（選填）','300×60 px；JPG／GIF／PNG；≤150 KB；僅桌機顯示，可由頻道自動產生')];
  const safety=['Safe Zone：使用 Google 官方橫式、直式、方形安全區模板，重要文字、Logo、商品放在紅色安全區內。','UI 遮擋：預留底部播放控制、CTA／廣告資訊及直式右側互動按鈕；各裝置與活動不同，不套用固定百分比。','校稿：字數包含空白；英文與中文混用需合計，特殊符號與 emoji 在後台確認。','Landing URL：確認網址有效／產品已上架，建議加上 UTM 追蹤參數。'];
  const copy=[f('headline','標題',15,false,'CTA 短標題；有使用 CTA 時提供。'),f('cta','CTA',10,false,'可用按鈕依後台。')];
  const definitions=[
    {id:'google-skippable',name:'YouTube｜可跳過串流廣告',source:g(6055025),fields:copy.map(x=>({...x})),rules:[...video,r('長度限制','一般競價無格式最低／最高長度；預訂型 12 秒–6 分鐘'),r('建議長度','認知／行動 15–20 秒；考慮 2–3 分鐘','官方建議'),r('播放機制','影片前／中／後播放；觀看 5 秒後可跳過')],visual:banner,notes:['5 秒黃金原則：因第 5 秒起可跳過，建議前 5 秒帶出品牌與主要訊息；這是製作建議，不是審核限制。','單一串流短標題 15、CTA 10。若用多格式 VRC，另填長標題 90 與說明 90；本表以條件欄位列出，不用選單切換。'],conditional:[f('longHeadline','長標題',90,false,'多格式 VRC 必填。',{requirement:'多格式 VRC 必填'}),f('description','說明',90,false,'多格式 VRC 必填。',{requirement:'多格式 VRC 必填'})]},
    {id:'google-nonskippable',name:'YouTube｜不可跳過串流廣告',source:g(11462260),fields:copy.map(x=>({...x,required:true,requirement:'本表交付必填'})),rules:[...video,r('長度限制','標準 7–15 秒；CTV 16–30 秒；≤6 秒屬 Bumper'),r('CTV 30 秒素材','必須橫式；方形與直式不能投放此格式'),r('播放機制','影片前／中／後播放，無跳過按鈕')],visual:banner,notes:['標準版與 CTV 請由投放人員確認；不將 30 秒套用所有装置。','在開頭快速呈現品牌、主張；不可跳過仍需避免過長鋪陳。','本格式不要求 In-feed 的兩行說明，也不一律要求長標題。']},
    {id:'google-bumper',name:'YouTube｜Bumper Ads',source:g(11462260),fields:copy.map(x=>({...x})),rules:[...video,r('長度限制','最多 6 秒；不將 5 秒設成所有活動的最低限制'),r('播放機制','影片前／中／後播放，不可跳過')],visual:banner,notes:['6 秒內聚焦一個訊息，及早帶出品牌；避免多段長文案。','短標題 15、CTA 10；必要性依 VRC 建立方式，未使用 CTA 時不強制交付。','多格式 VRC 另需長標題 90 與說明 90，與 6 秒影片長度分開判斷。'],conditional:[f('longHeadline','長標題',90,false,'多格式 VRC 必填。',{requirement:'多格式 VRC 必填'}),f('description','說明',90,false,'多格式 VRC 必填。',{requirement:'多格式 VRC 必填'})]},
    {id:'google-shorts',name:'YouTube｜YouTube Shorts 廣告',source:shorts,fields:[f('headline','標題',40,false,'官方 Shorts CTA overlay 建議交付；若活動限制較短，以該活動為準。',{mode:'recommendation'}),f('description','說明',90,true,'官方輸入上限 90；行數隨裝置而變。'),f('cta','CTA',10,false,'10 為 VRC 自訂 CTA 上限；其他活動使用後台選項。')],rules:[...video,r('製作比例','建議 9:16、1080×1920 px；橫式／方形亦支援','官方建議'),r('長度／播放','最長 3 分鐘；Shorts feed 只播前 60 秒，第 50 秒可出現前往觀看頁提示'),r('建議長度','小於 60 秒；導流製作建議 10–30 秒','官方建議'),r('播放機制','穿插於 Shorts；可立即上下滑動跳過'),r('CTA 出現時間','Demand Gen／PMax／App：3 秒；Video Views／Video Reach：10 秒')],visual:[r('視覺素材','以直式影片為主；Shorts 不另交 300×60 桌機 Companion Banner'),r('文字顯示','說明：手機超過 1 行、桌機／TV 超過 2 行可能截斷')],notes:['立即可滑走，前幾秒就呈現主題與品牌，不能把串流的 5 秒不可跳過套用 Shorts。','使用直式安全區模板，避開右側互動工具與下方 CTA、頻道名稱、說明。','多格式 VRC 的共用長標題 90／說明 90 為條件欄位；40 字標題是 Shorts overlay 官方建議，不是所有活動同一硬性限制。'],conditional:[f('longHeadline','長標題',90,false,'多格式 VRC 必填。',{requirement:'多格式 VRC 必填'})]},
    {id:'google-infeed',name:'YouTube｜In-Feed 影音廣告',source:g(6227733),fields:[f('headline','標題',100,true,'官方 Available assets 主文：100 字元；Recommended 表列兩行各 40，部分裝置 >25 即可能縮短。'),f('descriptions','說明行',35,false,'每行 35，最多 2 行；合計最多 70 字元不代表可填一行 70。',{min:0,max:2})],rules:[...video,r('長度','格式頁接受任何長度；活動可能另有限制'),r('播放機制','YouTube 首頁／搜尋／接續觀看等；點擊縮圖進入觀看或目標頁，部分環境滑鼠停留／動態內可靜音自動播放')],visual:[r('影片縮圖','可選影片產生的 4 張縮圖；自訂圖需在 YouTube Studio 設定'),r('自訂縮圖規格','建議 1280×720、16:9；最低 1280×640；JPG／GIF／PNG；<2 MB'),r('Companion Banner','不將串流桌機 300×60 Banner 列為 In-feed 必交素材')],notes:['35／70 是半形字元額度：2 行各 35，合計 70；純中文每行保守建議 17 字，兩行 34 字。','首頁贊助影片卡不保證顯示說明或獨立 CTA；桌機觀看頁與 TV 不顯示說明。','多格式 VRC 使用長標題 90、說明 90；這是活動共用欄位，不能與格式頁 100／35 混為同一限制。'],conditional:[f('longHeadline','長標題',90,false,'多格式 VRC 必填；取代活動的格式標題。',{requirement:'多格式 VRC 必填'}),f('description','活動說明',90,false,'多格式 VRC 必填；不與 35 字說明行混填。',{requirement:'多格式 VRC 必填'})]},
    {id:'google-action',name:'YouTube｜影音行動廣告（現行 Demand Gen）',source:action,fields:[f('headline','標題',40,true,'現行 Demand Gen 上限 40；舊 VAC 30 不再當現行限制。',{requirement:'本表交付必填'}),f('longHeadline','長標題',90,true,'用於 In-feed。',{requirement:'本表交付必填'}),f('description','說明',90,true,'官方建議至少交付 3 則不同文案。',{requirement:'本表交付必填'}),f('business','商家名稱',25,true),f('cta','CTA',null,false,'由後台可用選項選擇；不將 VRC 自訂 CTA 10 強加在所有 Demand Gen。')],rules:[...video,r('現行狀態','VAC 已於 2026 年 5 月全部升級 Demand Gen；此表交付現行替代格式'),r('影片數量／長度','每廣告 1–5 支；至少 5 秒；要投串流至少 10 秒'),r('比例補充','亦接受 4:5，建議 1080×1350 px'),r('播放機制','依串流／In-feed／Shorts 等版位播放；串流可跳過，Shorts 可立即滑走')],visual:[r('Logo','方形；建議 1200×1200；交付至少 144×144 px；≤150 KB'),r('官方文件差異','Logo 素材表列最低 128×128，影片廣告表列 144×144；交付採較高尺寸','文件差異'),r('Companion Banner','現行影片素材表以 Logo 為需求，不將 300×60 列為本表必交')],notes:['影音行動廣告保留獨立分類，但標示已由 Demand Gen 取代，避免提交已停用活動。','官方建議至少 3 則不同標題、長標題與說明；客戶可在每組欄位以換行提供多則，勿複製相同文案。','串流前 5 秒快速呈現品牌與主張；不同版位的 CTA 與說明可能改變或截斷。'],extraSources:[{label:'VAC 升級公告',url:g(10147229)}]}
  ];
  const forms=definitions.map(d=>({...d,platform:'Google',category:'影片',counting:'google',checked:'2026-10-06',videoUrl:true,ytIndependent:true,fields:[...d.fields,...(d.conditional||[])],notes:[...d.notes,...safety],sourceMore:[{label:'通用影片／Safe Zone 官方模板',url:technical},{label:'Google Ads 活動欄位規格',url:reach},...(d.extraSources||[])],previewId:d.id,sections:['1. 影音規格與長度限制','2. 核心文案需求與字數限制','3. Companion Banner／視覺圖文規格','4. 進稿校稿重點與注意事項']}));
  const keep=catalog.formats.filter(s=>!s.id.startsWith('google-')||['google-rsa','google-rda'].includes(s.id));
  const index=keep.findIndex(s=>s.platform==='LINE LAP');keep.splice(index,0,...forms);
  window.AD_SPECS={...catalog,formats:keep,version:'2026.10.06-YT29',resolveSpec:id=>keep.find(s=>s.id===id),schedule:{...catalog.schedule,text:'官方查核 10/06 · YT 依格式獨立表單'}};
})();
